Mobile page
GordonOtieno/concert pull request #1
Opened 2022-07-27 13:16 UTC by GordonOtieno

**Created Lawyers hub web concert**
 - created index page.
 - created about page
 - Adopted the pages to both mobile and desktop view
 - created hamburger menu with functional (X)  button.
 - added functional links to both pages.
 - implemented dynamic rendering of speakers using js objects.
 - recorded loom video link: https://www.loom.com/share/b5a284a8ae594ca79940a9a2a19c19e9

2022-07-27 14:02 UTC, Bondok6 requested changes
## Hi @GordonOtieno 🙋‍♂️, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## To Highlight 
- No linter errors ✅
- Professional README.md file ✅
- Your repo is professional ✅
- Great job on implementing the Artists section dynamically ✅

## Suggested changes

- [ ] According to the requirements, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:

![image](https://user-images.githubusercontent.com/45231276/181190349-2026da67-36fe-4bbe-811b-e2efd8c98b32.png)

- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-27 14:02 UTC, Bondok6 commented on README.md
>  This project is [MIT](./MIT.md) licensed.
- [ ] Great job using Microverse Template here 💯👌 but you forgot to customize your `MIT.md` file, so kindly add your name and customize it 😉

> The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯

2022-07-27 14:02 UTC, Bondok6 commented on README.md
> -
- [ ] Your README is well documented :100: but I would suggest adding the `Acknowledgements` section to give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/) :wink: :pushpin:

![-1](https://user-images.githubusercontent.com/45231276/181178654-ec00dfb0-1990-40d1-b370-0f6dc8f01606.PNG)

2022-07-27 14:02 UTC, Bondok6 commented on README.md
> +[Lawyers Hub](https://gordonotieno.github.io/concert/)
- [ ] The live demo link is broken, kindly fix it 👌 According to the requirements you should deploy your project using Github Pages 💯

![image](https://user-images.githubusercontent.com/45231276/181259598-6e1ade4d-86b4-41b2-ba3d-37ae6fb8cb67.png)

2022-07-27 14:02 UTC, Bondok6 commented on .vscode/settings.json
> +}
- [OPTIONAL] since this is your own VSCode setting. it doesn't necessarily need to be committed into the repo. so having this in the .gitignore file may be a good choice 👍

2022-07-27 14:02 UTC, Bondok6 commented on about.html
> +    </footer>
- [ ] According to the original design, the about page should be shown the partners section and the footer section on the `mobile version`, so kindly add the partners (sponsors) section on the mobile version 💯👌

| Your Design  | Original Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/181260991-c8030a7e-d16a-456f-bfd1-73a7448dca61.PNG" width="500" />  | <img src="https://user-images.githubusercontent.com/45231276/181187188-a206356f-c7c1-47a8-a2f7-c4e56b39c84e.PNG" width="500" /> |


- [ ] Also, in the original design the footer section has a dark (black) background-color on `the Desktop version`, So kindly change the background-color from white to black on `the Desktop version`, remember The pages should look almost identical to the original design 👌

| Your Design  | Original Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/181262504-1497e3c0-8d5e-4fcc-aa0a-4469c115200e.PNG" width="500" />  | <img src="https://user-images.githubusercontent.com/45231276/181262424-f012e340-a19c-4492-ab90-d0212098458e.PNG" width="500" /> |

2022-07-27 14:02 UTC, Bondok6 commented on index.html
> +    </section>
- [ ] According to the requirements and the original design, You should follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including Colors, Typography, and Layout.
The main programs section doesn't look similar to the original design, so kindly use the same font-colors and remove the `read more` button, and add the horizontal line below the title 👌💯

| Your Design  | Original Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/181265557-79d56bf3-be93-4867-a941-a9401f6a4a3e.PNG" width="500" />  | <img src="https://user-images.githubusercontent.com/45231276/181265627-fe7ea2d0-26b7-4475-b26e-ff369ebdde83.PNG" width="500" /> |

- [ ] Also, on the mobile version, you should update/change the style of the `SEE THE WHOLE PROGRAM` Link 👌

| Your Design  | Original Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/181266211-4f6acb5a-9327-4fde-94ad-7d2e5d71ff2f.PNG" width="500" />  | <img src="https://user-images.githubusercontent.com/45231276/181266102-bcbcac63-9707-44de-b805-4acf0219c319.PNG" width="500" /> |

2022-07-27 14:14 UTC, Bondok6 commented on index.html
> +    </footer>
- [x] According to the original design, the `partners` and `footer` sections should not be shown in the **mobile version**, the last section for the `mobile version` should be the speakers (or the artists in your project). Please, kindly address this issue in the mobile version in order to match the design :smiley: :raised_hands:

| Original design | Your design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/81522435/147131660-823d562f-6346-4262-9854-f7292853388d.png) | ![image](https://user-images.githubusercontent.com/45231276/181269454-72db69bc-e0c4-4551-97a3-f3ba8eeda0c5.PNG) |

2022-07-28 14:30 UTC, OLIPLICHE approved these changes
Hi @GordonOtieno, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Linter is green (the last commit have a green check mark (✅)) 👏
README file is descriptive 👏
Commit messages are meaningful 👏 👏
Github flow is correctly used (Pull Request is made from the feature branch into the main branch) 👏

## OPTIONAL

- [ ] Desktop version:
- Please the high of the footer is too much, I suggest you resize it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 14:34 UTC, merged